stages:
  - make_assets
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      - chapters/introduction/lecture
      # - chapters/protocol/lecture
      # - chapters/case-study/lecture/slides
      # - chapters/wallet/lecture/slides
      # - chapters/vm/lecture
      # - chapters/smart-contracts/lecture
      # - chapters/security/lecture
      # - chapters/dApps/lecture
      # - chapters/composability/lecture
    args:
      - all

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      Introduction: slides/introduction
      Protocol: slides/protocol
      # Case-Study: slides/case-study
      # Wallet: slides/wallet
      VM: slides/vm
      Smart-Contracts: slides/smart-contracts
      Security: slides/security
      Dapps: slides/dApps
      Composability: slides/composability

docusaurus:
  plugin: docusaurus
  options:
    course_name: Blockchain Protocols and Distributed Applications
    sidebar: js
    structure:
      - Introduction: chapters/README.md
      - Lecture:
          path: /build/embed_reveal
          subsections:
            - Introduction: Introduction/Introduction.mdx
            # - Blockchain Protocols: Blockchain-Protocols/Blockchain-Protocols.mdx
            # - Case Study: Case-Study/Case-Study.mdx
            # - Wallet: Wallet/Wallet.mdx
            # - Virtual Machine: Virtual-Machine/Virtual-Machine.mdx
            # - Smart Contracts: Smart-Contracts/Smart-Contracts.mdx
            # - Security: Security/Security.mdx
            # - Scaling dApps: Scaling-dApps/Scaling-dApps.mdx
            # - Composability: Composability/Composability.mdx
      - Practical Sessions:
          - Explorer:
              path: chapters/introduction/lab/content/explorer
              extra:
                - ../../media/
                # - ../../quiz/
              subsections:
                - Time in Blockchain/: time.md
                - Blocks/: blocks.md
                - Block Leader/: leader.md
                - Consensus Grup/: consensus.md
                - Transactions/: transactions.md
                - Blockchain Validators/: validators.md
                - Blockchain Observers/: observers.md
                - Devnet Blockchains/: devnet_testnet.md
          - Observer:
              path: chapters/introduction/lab/content/observer/
              extra:
                - ../../media/
                # - ../../quiz/
              subsections:
                - Observers: observer.md


          - Wallet:
              path: chapters/introduction/lab/content/wallet
              extra:
                - ../../media/
                # - ../../quiz/
              subsections:
                - Wallet/: wallet.md
                - Keystore/: keystore.md
                - Access & Faucet: faucet.md
                - Send Transaction: send_tx.md
                - Browser Web Wallet: browser_wallet.md
                - Observer: observer.md
      #     - Basic Peer-to-Peer Blockchain:
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      #     - Observers:
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      #     - Virtual Machine:
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      #     - Smart Contracts:
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      #     - Fungible Tokens:
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      #     - Non Fungible Tokens (NFT):
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      #     - dApps:
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      #     - Security:
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      #     - DeFi:
      #         path: chapters/template-chapter/yet-another-topic/
      #         subsections:
      #           - Drills/: drills/
      - Assignments:
          - Project: assignments/project.md
          - Blockchain Research Assignment: assignments/blockchain_research_assignment.md
          - Scientific Research Assignment: assignments/scientific_research_assignment.md
              # path: assignments/
              # extra:
              #   - media/
              # subsections:
              #   - Reading/: reading/
              #   - Drills/: drills/
              #   - Guides/: guides/
                # - Slides: /build/embed_reveal/template-chapter-template-topic
      - Grading: util/grading.md
      - Resources: util/resources.md
    # static_assets:
    #   - slides/Compute: /build/make_assets/content/chapters/introduction/lecture/_site
    config_meta:
      title: Blockchain Protocols and Distributed Applications
      url: http://costincarabas.github.io/
      baseUrl: /blockchain-protocols-and-distributed-applications/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      Main site: https://ocw.cs.pub.ro/courses/fob
      OCW: https://ocw.cs.pub.ro/courses/fob
      Facebook: https://www.facebook.com/zuck/
    copyright_string: Example Copyright
